name: jawaramobile_1
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  data_table_2: ^2.5.10
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.10.0
  go_router: ^16.2.4
  image_picker: ^0.8.7+6
  file_picker: ^8.0.3
  fl_chart: ^1.1.1
  postgresql2: ^1.7.0
  http: ^1.6.0
  google_fonts: ^6.3.2
  flutter_animate: ^4.5.2
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo/logo.png"
