name: jawaramobile_1
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  data_table_2: ^2.5.10
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.10.0
  go_router: ^17.0.0
  image_picker: ^1.2.1
  file_picker: ^10.3.7
  fl_chart: ^1.1.1
  postgresql2: ^1.7.0
  http: ^1.6.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.3.2
  flutter_animate: ^4.5.2
  lottie: ^3.3.2
  logger: ^2.6.2
  camera: ^0.11.0+2
  path_provider: ^2.1.4
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo/logo.png"
